stages:
  - test

before_script:
  - echo "USER INFO"
  - echo $PATH
  - echo $USER
  - uname -a
  - which python
  - which cargo
  - python --version
  - cargo --version
  - python -m venv .venv
  - source .venv/bin/activate

variables:
  GIT_STRATEGY: clone

debug:
  stage: test
  only:
    - merge_requests
    - web
    - schedules
  tags:
    - linux
  artifacts:
    paths:
      - test.out
    expire_in: 1 week
    when: always
  script:
    - cargo clean
    - cargo update
    - cargo build
    - cargo test -- --nocapture |& tee test.out

debug_py:
  stage: test
  only:
    - merge_requests
    - web
    - schedules
  tags:
    - linux
  artifacts:
    paths:
      - test_py.out
    expire_in: 1 week
    when: always
  script:
    - pip install -e .[plot,fem,diffrax,rust]
    - maturin develop --release --features python
    - pytest |& tee test_py.out

release:
  stage: test
  only:
    - merge_requests
    - web
    - schedules
  tags:
    - linux
  artifacts:
    paths:
      - test_rel.out
    expire_in: 1 week
    when: always
  script:
    - cargo clean
    - cargo update
    - cargo build --release
    - cargo test --release |& tee test_rel.out
