[package]
name = "ormatex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ormatex"
crate-type = ["cdylib", "rlib"]
path = 'src/lib.rs'

[features]
default = ["python"]
plot = ["dep:kuva"]
python = ["dep:pyo3", "dep:numpy", "dep:ndarray", "dep:faer-ext"]

[dependencies]
thiserror = "1.0"
assert_approx_eq = "1.1.0"
num-traits = "0.2.18"
num-complex = "0.4"
reborrow = "0.5.5"
rayon = "*"
libm = "0.2.8"
rand = "0.8.5"
rand_distr = "0.4.3"
statrs = "0.18.0"
csv = "1.4.0"
flexi_logger = "0.31"
log = "0.4"

# faer lin alg
faer = {version = "0.23.2", features=["unstable",]}
faer-traits = "0.23.0"
faer_gmres = "0.4.1"

# nd
ndelement = {git = "https://codeberg.org/nd-project/nd.git"}
ndmesh = {git = "https://codeberg.org/nd-project/nd.git"}
ndfunctionspace = {git = "https://codeberg.org/nd-project/nd.git"}
rlst = "0.6"
quadraturerules = "0.12.0"

# optional deps
kuva = {version="0.1", optional=true}

# python binding deps
pyo3 = {version="=0.26", features = ["extension-module"], optional=true}
numpy = {version="0.26", optional=true}
ndarray = {version=">=0.16", features=["rayon"], optional=true}
faer-ext = {version="0.7.0", features=["ndarray", "numpy"], optional=true}

[tool.maturin]
module-name = "ormatex"
profile = "release"
editable-profile = "release"
features = ["python"]
