[build-system]
requires = ["setuptools >= 64", "maturin>=1.0,<2.0"]
build-backend = "setuptools.build_meta"
# build-backend = "maturin"

[project]
name = "ormatex_py"
version = "0.0.1"
#dynamic = ["version"]
authors = [
    {name = "William Gurecky", email = "gureckywl@ornl.gov"},
    {name = "Konstantin Pieper", email = "pieperk@ornl.gov"},
]
description = "Matrix exponential routines and exponential time integrators"
readme = "README.md"
requires-python = ">=3.8"
keywords = [ "matrix exponential", "time integration", "exponential time integration"]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
]
dependencies = [
    "numpy>=1.8.0",
    "scipy>=0.12.0",
    "jax>=0.10.2",
    "equinox>=0.13.8",
    "pytest",
    "mpmath",
]

[project.optional-dependencies]
rust = ["maturin"]
plot = ["matplotlib"]
fem = ["scikit-fem"]
diffrax = ["diffrax", "optimistix", "lineax"]

#[project.scripts]
#my-script = "my_package.module:function"

#[tool.setuptools.packages]
#find = {namespaces = false}  # Disable implicit namespaces

[tool.setuptools]
packages = ["ormatex_py"]

[tool.maturin]
module-name = "ormatex_py.ormatex"
