[package]
name = "ormatex_sem_nd"
version = "0.1.0"
edition = "2021"

[dependencies]
faer = { version = "0.23.2", features = ["unstable"] }
ndelement = { git = "https://codeberg.org/nd-project/nd.git" }
ndmesh = { git = "https://codeberg.org/nd-project/nd.git" }
ndfunctionspace = { git = "https://codeberg.org/nd-project/nd.git" }
rlst = "0.6"
quadraturerules = "0.12.0"
rayon = "1"

[dev-dependencies]
ormatex = { path = "..", default-features = false }

[[example]]
name = "navier-stokes-cylinder"
path = "examples/navier-stokes/cylinder.rs"

[[example]]
name = "navier-stokes-pipe"
path = "examples/navier-stokes/pipe.rs"

[[example]]
name = "navier-stokes-cavity"
path = "examples/navier-stokes/cavity.rs"

[[example]]
name = "navier-stokes-cavity-comp"
path = "examples/navier-stokes/cavity_comp.rs"
