[package]
name = "ormatex_sem_nd"
version = "0.1.0"
edition = "2021"

[dependencies]
faer = { version = "0.23", features = ["unstable"] }
ndelement = { git = "https://codeberg.org/nd-project/nd.git" , rev = "28211441c0"}
ndmesh = { git = "https://codeberg.org/nd-project/nd.git" , rev = "28211441c0"}
ndfunctionspace = { git = "https://codeberg.org/nd-project/nd.git" , rev = "28211441c0"}
rlst = "0.6"
quadraturerules = "0.12.0"
rayon = "1"
pulp = "0.21.5"

[dev-dependencies]
ormatex = { path = "..", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
blas-src = { version = "0.14", features = ["accelerate"] }
lapack-src = { version = "0.13", features = ["accelerate"] }

[target.'cfg(target_os = "linux")'.dependencies]
openblas-src = { version = "0.10", features = ["system"] }
lapack-src = { version = "0.13", features = ["openblas"] }
blas-src = { version = "0.14", features = ["openblas"] }

[[example]]
name = "navier-stokes-cylinder"
path = "examples/navier-stokes/cylinder.rs"

[[example]]
name = "navier-stokes-pipe"
path = "examples/navier-stokes/pipe.rs"

[[example]]
name = "navier-stokes-cavity"
path = "examples/navier-stokes/cavity.rs"

[[example]]
name = "navier-stokes-cavity-comp"
path = "examples/navier-stokes/cavity_comp.rs"

[[example]]
name = "navier-stokes-cavity-comp-tensor"
path = "examples/navier-stokes/cavity_comp_tensor.rs"

[[example]]
name = "navier-stokes-cavity-comp-generic"
path = "examples/navier-stokes/cavity_comp_generic.rs"

[[example]]
name = "navier-stokes-cylinder-tensor"
path = "examples/navier-stokes/cylinder_tensor.rs"

[[example]]
name = "navier-stokes-cylinder-generic"
path = "examples/navier-stokes/cylinder_generic.rs"

[[example]]
name = "navier-stokes-backward-step-tensor"
path = "examples/navier-stokes/backward_step_tensor.rs"

[[example]]
name = "navier-stokes-de-vahl-davis-cavity"
path = "examples/navier-stokes/de_vahl_davis_cavity.rs"
